2024-01-26 14:51:16 ERROR Elements not present after 0.5 seconds on page: https://capital.com/ro/trade-platinum
2024-01-26 14:51:16 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5592aa4aaf83 <unknown>
#1 0x5592aa163cf7 <unknown>
#2 0x5592aa1b399e <unknown>
#3 0x5592aa1b3aa1 <unknown>
#4 0x5592aa1fed64 <unknown>
#5 0x5592aa1dd0dd <unknown>
#6 0x5592aa1fc006 <unknown>
#7 0x5592aa1dce53 <unknown>
#8 0x5592aa1a4dd4 <unknown>
#9 0x5592aa1a61de <unknown>
#10 0x5592aa46f531 <unknown>
#11 0x5592aa473455 <unknown>
#12 0x5592aa45bf55 <unknown>
#13 0x5592aa4740ef <unknown>
#14 0x5592aa43f99f <unknown>
#15 0x5592aa498008 <unknown>
#16 0x5592aa4981d7 <unknown>
#17 0x5592aa4aa124 <unknown>
#18 0x7f8804294ac3 <unknown>

2024-01-26 14:51:21 ERROR Elements not present after 0.5 seconds on page: https://capital.com/ro/trade-platinum
2024-01-26 14:51:21 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5592aa4aaf83 <unknown>
#1 0x5592aa163cf7 <unknown>
#2 0x5592aa1b399e <unknown>
#3 0x5592aa1b3aa1 <unknown>
#4 0x5592aa1fed64 <unknown>
#5 0x5592aa1dd0dd <unknown>
#6 0x5592aa1fc006 <unknown>
#7 0x5592aa1dce53 <unknown>
#8 0x5592aa1a4dd4 <unknown>
#9 0x5592aa1a61de <unknown>
#10 0x5592aa46f531 <unknown>
#11 0x5592aa473455 <unknown>
#12 0x5592aa45bf55 <unknown>
#13 0x5592aa4740ef <unknown>
#14 0x5592aa43f99f <unknown>
#15 0x5592aa498008 <unknown>
#16 0x5592aa4981d7 <unknown>
#17 0x5592aa4aa124 <unknown>
#18 0x7f8804294ac3 <unknown>