2024-01-26 15:46:30 ERROR Elements not present after 0.5 seconds on page: https://capital.com/it/macd
2024-01-26 15:46:30 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55b90e5f5f83 <unknown>
#1 0x55b90e2aecf7 <unknown>
#2 0x55b90e2fe99e <unknown>
#3 0x55b90e2feaa1 <unknown>
#4 0x55b90e349d64 <unknown>
#5 0x55b90e3280dd <unknown>
#6 0x55b90e347006 <unknown>
#7 0x55b90e327e53 <unknown>
#8 0x55b90e2efdd4 <unknown>
#9 0x55b90e2f11de <unknown>
#10 0x55b90e5ba531 <unknown>
#11 0x55b90e5be455 <unknown>
#12 0x55b90e5a6f55 <unknown>
#13 0x55b90e5bf0ef <unknown>
#14 0x55b90e58a99f <unknown>
#15 0x55b90e5e3008 <unknown>
#16 0x55b90e5e31d7 <unknown>
#17 0x55b90e5f5124 <unknown>
#18 0x7f15c4094ac3 <unknown>

2024-01-26 15:46:36 ERROR Elements not present after 0.5 seconds on page: https://capital.com/it/macd
2024-01-26 15:46:36 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55b90e5f5f83 <unknown>
#1 0x55b90e2aecf7 <unknown>
#2 0x55b90e2fe99e <unknown>
#3 0x55b90e2feaa1 <unknown>
#4 0x55b90e349d64 <unknown>
#5 0x55b90e3280dd <unknown>
#6 0x55b90e347006 <unknown>
#7 0x55b90e327e53 <unknown>
#8 0x55b90e2efdd4 <unknown>
#9 0x55b90e2f11de <unknown>
#10 0x55b90e5ba531 <unknown>
#11 0x55b90e5be455 <unknown>
#12 0x55b90e5a6f55 <unknown>
#13 0x55b90e5bf0ef <unknown>
#14 0x55b90e58a99f <unknown>
#15 0x55b90e5e3008 <unknown>
#16 0x55b90e5e31d7 <unknown>
#17 0x55b90e5f5124 <unknown>
#18 0x7f15c4094ac3 <unknown>