2024-01-26 15:31:59 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/rohstoffhandel
2024-01-26 15:31:59 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x555c8c251f83 <unknown>
#1 0x555c8bf0acf7 <unknown>
#2 0x555c8bf5a99e <unknown>
#3 0x555c8bf5aaa1 <unknown>
#4 0x555c8bfa5d64 <unknown>
#5 0x555c8bf840dd <unknown>
#6 0x555c8bfa3006 <unknown>
#7 0x555c8bf83e53 <unknown>
#8 0x555c8bf4bdd4 <unknown>
#9 0x555c8bf4d1de <unknown>
#10 0x555c8c216531 <unknown>
#11 0x555c8c21a455 <unknown>
#12 0x555c8c202f55 <unknown>
#13 0x555c8c21b0ef <unknown>
#14 0x555c8c1e699f <unknown>
#15 0x555c8c23f008 <unknown>
#16 0x555c8c23f1d7 <unknown>
#17 0x555c8c251124 <unknown>
#18 0x7f9d27e94ac3 <unknown>

2024-01-26 15:32:05 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/rohstoffhandel
2024-01-26 15:32:05 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x555c8c251f83 <unknown>
#1 0x555c8bf0acf7 <unknown>
#2 0x555c8bf5a99e <unknown>
#3 0x555c8bf5aaa1 <unknown>
#4 0x555c8bfa5d64 <unknown>
#5 0x555c8bf840dd <unknown>
#6 0x555c8bfa3006 <unknown>
#7 0x555c8bf83e53 <unknown>
#8 0x555c8bf4bdd4 <unknown>
#9 0x555c8bf4d1de <unknown>
#10 0x555c8c216531 <unknown>
#11 0x555c8c21a455 <unknown>
#12 0x555c8c202f55 <unknown>
#13 0x555c8c21b0ef <unknown>
#14 0x555c8c1e699f <unknown>
#15 0x555c8c23f008 <unknown>
#16 0x555c8c23f1d7 <unknown>
#17 0x555c8c251124 <unknown>
#18 0x7f9d27e94ac3 <unknown>