2024-01-26 15:50:21 ERROR Elements not present after 0.5 seconds on page: https://capital.com/it/negozia-petrolio-brent
2024-01-26 15:50:21 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x562933e34f83 <unknown>
#1 0x562933aedcf7 <unknown>
#2 0x562933b3d99e <unknown>
#3 0x562933b3daa1 <unknown>
#4 0x562933b88d64 <unknown>
#5 0x562933b670dd <unknown>
#6 0x562933b86006 <unknown>
#7 0x562933b66e53 <unknown>
#8 0x562933b2edd4 <unknown>
#9 0x562933b301de <unknown>
#10 0x562933df9531 <unknown>
#11 0x562933dfd455 <unknown>
#12 0x562933de5f55 <unknown>
#13 0x562933dfe0ef <unknown>
#14 0x562933dc999f <unknown>
#15 0x562933e22008 <unknown>
#16 0x562933e221d7 <unknown>
#17 0x562933e34124 <unknown>
#18 0x7f14ce294ac3 <unknown>

2024-01-26 15:50:29 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-26 15:50:29 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x562933e34f83 <unknown>
#1 0x562933aedcf7 <unknown>
#2 0x562933b3d99e <unknown>
#3 0x562933b3daa1 <unknown>
#4 0x562933b88d64 <unknown>
#5 0x562933b670dd <unknown>
#6 0x562933b86006 <unknown>
#7 0x562933b66e53 <unknown>
#8 0x562933b2edd4 <unknown>
#9 0x562933b301de <unknown>
#10 0x562933df9531 <unknown>
#11 0x562933dfd455 <unknown>
#12 0x562933de5f55 <unknown>
#13 0x562933dfe0ef <unknown>
#14 0x562933dc999f <unknown>
#15 0x562933e22008 <unknown>
#16 0x562933e221d7 <unknown>
#17 0x562933e34124 <unknown>
#18 0x7f14ce294ac3 <unknown>

2024-01-26 15:50:34 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-26 15:50:34 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x562933e34f83 <unknown>
#1 0x562933aedcf7 <unknown>
#2 0x562933b3d99e <unknown>
#3 0x562933b3daa1 <unknown>
#4 0x562933b88d64 <unknown>
#5 0x562933b670dd <unknown>
#6 0x562933b86006 <unknown>
#7 0x562933b66e53 <unknown>
#8 0x562933b2edd4 <unknown>
#9 0x562933b301de <unknown>
#10 0x562933df9531 <unknown>
#11 0x562933dfd455 <unknown>
#12 0x562933de5f55 <unknown>
#13 0x562933dfe0ef <unknown>
#14 0x562933dc999f <unknown>
#15 0x562933e22008 <unknown>
#16 0x562933e221d7 <unknown>
#17 0x562933e34124 <unknown>
#18 0x7f14ce294ac3 <unknown>

2024-01-26 15:50:40 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-26 15:50:40 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x562933e34f83 <unknown>
#1 0x562933aedcf7 <unknown>
#2 0x562933b3d99e <unknown>
#3 0x562933b3daa1 <unknown>
#4 0x562933b88d64 <unknown>
#5 0x562933b670dd <unknown>
#6 0x562933b86006 <unknown>
#7 0x562933b66e53 <unknown>
#8 0x562933b2edd4 <unknown>
#9 0x562933b301de <unknown>
#10 0x562933df9531 <unknown>
#11 0x562933dfd455 <unknown>
#12 0x562933de5f55 <unknown>
#13 0x562933dfe0ef <unknown>
#14 0x562933dc999f <unknown>
#15 0x562933e22008 <unknown>
#16 0x562933e221d7 <unknown>
#17 0x562933e34124 <unknown>
#18 0x7f14ce294ac3 <unknown>

2024-01-26 15:50:46 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-26 15:50:46 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x562933e34f83 <unknown>
#1 0x562933aedcf7 <unknown>
#2 0x562933b3d99e <unknown>
#3 0x562933b3daa1 <unknown>
#4 0x562933b88d64 <unknown>
#5 0x562933b670dd <unknown>
#6 0x562933b86006 <unknown>
#7 0x562933b66e53 <unknown>
#8 0x562933b2edd4 <unknown>
#9 0x562933b301de <unknown>
#10 0x562933df9531 <unknown>
#11 0x562933dfd455 <unknown>
#12 0x562933de5f55 <unknown>
#13 0x562933dfe0ef <unknown>
#14 0x562933dc999f <unknown>
#15 0x562933e22008 <unknown>
#16 0x562933e221d7 <unknown>
#17 0x562933e34124 <unknown>
#18 0x7f14ce294ac3 <unknown>