2024-01-26 15:41:08 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/aktienhandel
2024-01-26 15:41:08 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x564eb9e80f83 <unknown>
#1 0x564eb9b39cf7 <unknown>
#2 0x564eb9b8999e <unknown>
#3 0x564eb9b89aa1 <unknown>
#4 0x564eb9bd4d64 <unknown>
#5 0x564eb9bb30dd <unknown>
#6 0x564eb9bd2006 <unknown>
#7 0x564eb9bb2e53 <unknown>
#8 0x564eb9b7add4 <unknown>
#9 0x564eb9b7c1de <unknown>
#10 0x564eb9e45531 <unknown>
#11 0x564eb9e49455 <unknown>
#12 0x564eb9e31f55 <unknown>
#13 0x564eb9e4a0ef <unknown>
#14 0x564eb9e1599f <unknown>
#15 0x564eb9e6e008 <unknown>
#16 0x564eb9e6e1d7 <unknown>
#17 0x564eb9e80124 <unknown>
#18 0x7f742b694ac3 <unknown>

2024-01-26 15:41:17 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-26 15:41:17 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x564eb9e80f83 <unknown>
#1 0x564eb9b39cf7 <unknown>
#2 0x564eb9b8999e <unknown>
#3 0x564eb9b89aa1 <unknown>
#4 0x564eb9bd4d64 <unknown>
#5 0x564eb9bb30dd <unknown>
#6 0x564eb9bd2006 <unknown>
#7 0x564eb9bb2e53 <unknown>
#8 0x564eb9b7add4 <unknown>
#9 0x564eb9b7c1de <unknown>
#10 0x564eb9e45531 <unknown>
#11 0x564eb9e49455 <unknown>
#12 0x564eb9e31f55 <unknown>
#13 0x564eb9e4a0ef <unknown>
#14 0x564eb9e1599f <unknown>
#15 0x564eb9e6e008 <unknown>
#16 0x564eb9e6e1d7 <unknown>
#17 0x564eb9e80124 <unknown>
#18 0x7f742b694ac3 <unknown>

2024-01-26 15:41:22 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-26 15:41:22 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x564eb9e80f83 <unknown>
#1 0x564eb9b39cf7 <unknown>
#2 0x564eb9b8999e <unknown>
#3 0x564eb9b89aa1 <unknown>
#4 0x564eb9bd4d64 <unknown>
#5 0x564eb9bb30dd <unknown>
#6 0x564eb9bd2006 <unknown>
#7 0x564eb9bb2e53 <unknown>
#8 0x564eb9b7add4 <unknown>
#9 0x564eb9b7c1de <unknown>
#10 0x564eb9e45531 <unknown>
#11 0x564eb9e49455 <unknown>
#12 0x564eb9e31f55 <unknown>
#13 0x564eb9e4a0ef <unknown>
#14 0x564eb9e1599f <unknown>
#15 0x564eb9e6e008 <unknown>
#16 0x564eb9e6e1d7 <unknown>
#17 0x564eb9e80124 <unknown>
#18 0x7f742b694ac3 <unknown>

2024-01-26 15:41:28 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-26 15:41:28 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x564eb9e80f83 <unknown>
#1 0x564eb9b39cf7 <unknown>
#2 0x564eb9b8999e <unknown>
#3 0x564eb9b89aa1 <unknown>
#4 0x564eb9bd4d64 <unknown>
#5 0x564eb9bb30dd <unknown>
#6 0x564eb9bd2006 <unknown>
#7 0x564eb9bb2e53 <unknown>
#8 0x564eb9b7add4 <unknown>
#9 0x564eb9b7c1de <unknown>
#10 0x564eb9e45531 <unknown>
#11 0x564eb9e49455 <unknown>
#12 0x564eb9e31f55 <unknown>
#13 0x564eb9e4a0ef <unknown>
#14 0x564eb9e1599f <unknown>
#15 0x564eb9e6e008 <unknown>
#16 0x564eb9e6e1d7 <unknown>
#17 0x564eb9e80124 <unknown>
#18 0x7f742b694ac3 <unknown>

2024-01-26 15:41:34 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-26 15:41:34 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x564eb9e80f83 <unknown>
#1 0x564eb9b39cf7 <unknown>
#2 0x564eb9b8999e <unknown>
#3 0x564eb9b89aa1 <unknown>
#4 0x564eb9bd4d64 <unknown>
#5 0x564eb9bb30dd <unknown>
#6 0x564eb9bd2006 <unknown>
#7 0x564eb9bb2e53 <unknown>
#8 0x564eb9b7add4 <unknown>
#9 0x564eb9b7c1de <unknown>
#10 0x564eb9e45531 <unknown>
#11 0x564eb9e49455 <unknown>
#12 0x564eb9e31f55 <unknown>
#13 0x564eb9e4a0ef <unknown>
#14 0x564eb9e1599f <unknown>
#15 0x564eb9e6e008 <unknown>
#16 0x564eb9e6e1d7 <unknown>
#17 0x564eb9e80124 <unknown>
#18 0x7f742b694ac3 <unknown>