2024-01-26 16:08:52 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/que-puedes-operar-con-un-CFD
2024-01-26 16:08:52 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5578f02e3f83 <unknown>
#1 0x5578eff9ccf7 <unknown>
#2 0x5578effec99e <unknown>
#3 0x5578effecaa1 <unknown>
#4 0x5578f0037d64 <unknown>
#5 0x5578f00160dd <unknown>
#6 0x5578f0035006 <unknown>
#7 0x5578f0015e53 <unknown>
#8 0x5578effdddd4 <unknown>
#9 0x5578effdf1de <unknown>
#10 0x5578f02a8531 <unknown>
#11 0x5578f02ac455 <unknown>
#12 0x5578f0294f55 <unknown>
#13 0x5578f02ad0ef <unknown>
#14 0x5578f027899f <unknown>
#15 0x5578f02d1008 <unknown>
#16 0x5578f02d11d7 <unknown>
#17 0x5578f02e3124 <unknown>
#18 0x7f18aba94ac3 <unknown>

2024-01-26 16:08:58 ERROR Elements not present after 0.5 seconds on page: https://capital.com/es/que-puedes-operar-con-un-CFD
2024-01-26 16:08:58 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/SeleniumCapital/SeleniumCapital/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-cIj6ROMf-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5578f02e3f83 <unknown>
#1 0x5578eff9ccf7 <unknown>
#2 0x5578effec99e <unknown>
#3 0x5578effecaa1 <unknown>
#4 0x5578f0037d64 <unknown>
#5 0x5578f00160dd <unknown>
#6 0x5578f0035006 <unknown>
#7 0x5578f0015e53 <unknown>
#8 0x5578effdddd4 <unknown>
#9 0x5578effdf1de <unknown>
#10 0x5578f02a8531 <unknown>
#11 0x5578f02ac455 <unknown>
#12 0x5578f0294f55 <unknown>
#13 0x5578f02ad0ef <unknown>
#14 0x5578f027899f <unknown>
#15 0x5578f02d1008 <unknown>
#16 0x5578f02d11d7 <unknown>
#17 0x5578f02e3124 <unknown>
#18 0x7f18aba94ac3 <unknown>